### ISSUE TITLE
Add Rspec to test suites

### ISSUE THREAD

**Issue by devonestes** [exercism/xruby#384] opened 2016-06-24 17:06 UTC
I saw on [Twitter](https://twitter.com/samphippen/status/744293377794019329) that @samphippen recommended adding Rspec to the test suites, and @kytrinyx was cool with it. I think it's a good idea too, and I'd love to help in adding those specs.

I've been thinking about a way to do this that would be non-breaking, and what I've thought of for now is a command line flag when running the tests. Basically if you wanted to run your tests as they are now you can still do `ruby bob_test.rb` and all would work fine. But if you ran `ruby bob_test.rb RSPEC=true` then it would run the Rspec specs instead of minitest.

So, any thoughts? I think Sam's point that many bootcamp folks are using Rspec and having those tests in exercism would be helpful for their learning, but I can see that it might be confusing having two test suites in a file. We'd also need to update documentation significantly.

**Comment by kotp** [comment] 2016-06-25 09:17
See PR #381, and definitely let's get this figured out!

**Comment by kytrinyx** [comment] 2016-06-26 15:09
Closing this as a duplicate of #381.

@devonestes If you have any additional comments about it, would you mind adding them there? Cheers!

**Closed by kytrinyx** 2016-06-26 15:09 UTC
